# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170405_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='categories',
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
