# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_title',
        ),
    ]
