# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 08:47
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_project_project_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='body',
            new_name='body_personal',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='body_professional',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
