# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('home', '0009_auto_20170418_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectspage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
