# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('home', '0017_auto_20170510_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridsubpage',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='listsubpage',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
