# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20170510_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexpage',
            old_name='feed_image',
            new_name='header_image',
        ),
        migrations.AlterField(
            model_name='gridsubpage',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listsubpage',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
