# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('home', '0019_auto_20170510_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='link',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='linkspage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='project',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='project',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='project',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='projectspage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='projectssubpage',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='projectssubpage',
            name='page_ptr',
        ),
        migrations.AlterField(
            model_name='item',
            name='link_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AlterField(
            model_name='item',
            name='link_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='LinksPage',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectsPage',
        ),
        migrations.DeleteModel(
            name='ProjectsSubPage',
        ),
    ]
