# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20170510_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='body_header',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='contactpage',
            old_name='body_header',
            new_name='body',
        ),
    ]
